package DATOS;
// Generated 18-ago-2011 23:17:44 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 * Aula generated by hbm2java
 */
public class Aula  implements java.io.Serializable {


     private String idaula;
     private int capacidad;
     private Set edicions = new HashSet(0);

    public Aula() {
    }

	
    public Aula(String idaula, int capacidad) {
        this.idaula = idaula;
        this.capacidad = capacidad;
    }
    public Aula(String idaula, int capacidad, Set edicions) {
       this.idaula = idaula;
       this.capacidad = capacidad;
       this.edicions = edicions;
    }
   
    public String getIdaula() {
        return this.idaula;
    }
    
    public void setIdaula(String idaula) {
        this.idaula = idaula;
    }
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }
    public Set getEdicions() {
        return this.edicions;
    }
    
    public void setEdicions(Set edicions) {
        this.edicions = edicions;
    }

//******************************************************************************
public void Insertar() {

        try {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.getTransaction().begin();
            sesion.save(this);
            sesion.flush();
            sesion.getTransaction().commit();
            sesion.close();
            JOptionPane.showMessageDialog(null, "DATOS INSERTADOS CORRECTAMENTE.", "MENSAJE", JOptionPane.WARNING_MESSAGE, null);
        }catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
}

//------------------------------------------------------------------------------
public void Modificar() {

     try {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.getTransaction().begin();
            sesion.update(this);
            sesion.flush();
            sesion.getTransaction().commit();
            sesion.close();
            JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE.", "MENSAJE", JOptionPane.WARNING_MESSAGE, null);
        }catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
    }
//------------------------------------------------------------------------------
 public void Eliminar() {
          try {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.getTransaction().begin();
            sesion.delete(this);
            sesion.flush();
            sesion.getTransaction().commit();
            sesion.close();
            JOptionPane.showMessageDialog(null, "DATOS ELIMINADOS CORRECTAMENTE.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE, null);
        }catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
    }

//------------------------------------------------------------------------------

public boolean Existe(String id) {

        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();

        Iterator resultado = null;
        Object x = null;

        try {
            resultado = sesion.createSQLQuery("select IDAULA from aula where IDAULA='" + id + "'").list().iterator();

        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }

        while (resultado.hasNext()) {
            x = resultado.next();
            System.out.println("elemento id : " + x.toString());
        }
        sesion.close();
        if (x != null) {
            return true;
        } else {
            return false;
        }

    }
//------------------------------------------------------------------------------
    public List getListAula(){
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();
        List<Aula> t=null;
        try {
            t=sesion.createSQLQuery("select *from aula").list();
        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
        sesion.flush();
        sesion.close();
        return t;
    }
//------------------------------------------------------------------------------
    public Aula getAula(String id){
        Aula x = new Aula();
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();
        List<Object[]> t=null;
        try {
            t=sesion.createSQLQuery("select *from aula where IDAULA = '"+id+"'").list();
        } catch (HibernateException e) {
             System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
         sesion.flush();
         sesion.close();
        if(t.size()>0){
            x.setIdaula(t.get(0)[0].toString());
            x.setCapacidad(Integer.valueOf(t.get(0)[1].toString()));
            return x;
        }else{
             return null;
        }

    }
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------

//------------------------------------------------------------------------------


}


