package DATOS;
// Generated 19-ago-2011 9:46:36 by Hibernate Tools 3.2.1.GA



/**
 * CalificacionId generated by hbm2java
 */
public class CalificacionId  implements java.io.Serializable {


     private String idedicion;
     private String idempleado;

    public CalificacionId() {
    }

    public CalificacionId(String idedicion, String idempleado) {
       this.idedicion = idedicion;
       this.idempleado = idempleado;
    }
   
    public String getIdedicion() {
        return this.idedicion;
    }
    
    public void setIdedicion(String idedicion) {
        this.idedicion = idedicion;
    }
    public String getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(String idempleado) {
        this.idempleado = idempleado;
    }


    @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CalificacionId) ) return false;
		 CalificacionId castOther = ( CalificacionId ) other; 
         
		 return ( (this.getIdedicion()==castOther.getIdedicion()) || ( this.getIdedicion()!=null && castOther.getIdedicion()!=null && this.getIdedicion().equals(castOther.getIdedicion()) ) )
 && ( (this.getIdempleado()==castOther.getIdempleado()) || ( this.getIdempleado()!=null && castOther.getIdempleado()!=null && this.getIdempleado().equals(castOther.getIdempleado()) ) );
   }
   
    @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdedicion() == null ? 0 : this.getIdedicion().hashCode() );
         result = 37 * result + ( getIdempleado() == null ? 0 : this.getIdempleado().hashCode() );
         return result;
   }   


}


