package DATOS;
// Generated 18-ago-2011 23:17:44 by Hibernate Tools 3.2.1.GA

import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;




/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {

     private CalificacionId id;
     private Empleado empleado;
     private Edicion edicion;
     private int nota;

    public Calificacion() {
    }

	
    public Calificacion (CalificacionId id ,Empleado empleado,Edicion edicion) {
        this.id = id;
        this.empleado = empleado;
        this.edicion = edicion;
    }
    public Calificacion(CalificacionId id ,Empleado empleado,Edicion edicion, int nota) {
       this.id = id;
       this.empleado = empleado;
       this.edicion = edicion;
       this.nota = nota;
    }
   
    public Edicion getEdicion() {
        return this.edicion;
    }
    
    public void setEdicion(Edicion edicion) {
        this.edicion = edicion;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public int getNota() {
        return this.nota;
    }
    
    public void setNota(int nota) {
        this.nota = nota;
    }

    public CalificacionId getId() {
        return id;
    }

    public void setId(CalificacionId id) {
        this.id = id;
    }

//******************************************************************************
public void Insertar() {

        try {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.getTransaction().begin();
            sesion.save(this);
            sesion.flush();
            sesion.getTransaction().commit();
            sesion.close();
            JOptionPane.showMessageDialog(null, "DATOS INSERTADOS CORRECTAMENTE.", "MENSAJE", JOptionPane.WARNING_MESSAGE, null);
        }catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
}

//------------------------------------------------------------------------------
public void Modificar() {

     try {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.getTransaction().begin();
            sesion.update(this);
            sesion.flush();
            sesion.getTransaction().commit();
            sesion.close();
            JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE.", "MENSAJE", JOptionPane.WARNING_MESSAGE, null);
        }catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
    }
//------------------------------------------------------------------------------
 public void Eliminar() {
          try {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.getTransaction().begin();
            sesion.delete(this);
            sesion.flush();
            sesion.getTransaction().commit();
            sesion.close();
            JOptionPane.showMessageDialog(null, "DATOS ELIMINADOS CORRECTAMENTE.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE, null);
        }catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
    }

//------------------------------------------------------------------------------

public boolean Existe(String id) {

        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();

        Iterator resultado = null;
        Object x = null;

        try {
            resultado = sesion.createSQLQuery("select IDEMPLEADO from calificacion where IDEMPLEADO ='" + id + "'").list().iterator();

        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }

        while (resultado.hasNext()) {
            x = resultado.next();
            System.out.println("elemento id : " + x.toString());
        }
        sesion.close();
        if (x != null) {
            return true;
        } else {
            return false;
        }

    }
//------------------------------------------------------------------------------
    public List getListCalificacion(){
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();
        List<Calificacion> t=null;
        try {
            t=sesion.createSQLQuery("select *from calificacion").list();
        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
        sesion.flush();
        sesion.close();
        return t;
    }
//------------------------------------------------------------------------------
    public Calificacion getCalificacion(String id){
        Calificacion x = new Calificacion();
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();
        List<Object[]> t=null;
        try {
            t=sesion.createSQLQuery("select *from calificacion where IDEMPLEADO = '"+id+"'").list();
        } catch (HibernateException e) {
             System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
         sesion.flush();
         sesion.close();

        if(t.size()>0){
            x.setEmpleado(empleado.getEmpleado(t.get(0)[0].toString()));
            x.setEdicion(edicion.getEdicion(t.get(0)[1].toString()));
            x.setNota(Integer.valueOf(t.get(0)[2].toString()));
            return x;

        }else{
             return null;
        }

    }

//------------------------------------------------------------------------------
public List getListCalificacion(String id){
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();
        List<Calificacion> t=null;
        try {
            t=sesion.createSQLQuery("select *from calificacion where IDEMPLEADO = '"+id+"'").list();
        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
        sesion.flush();
        sesion.close();
        return t;
    }
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------



}


