package DATOS;
// Generated 19-ago-2011 9:46:36 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private String idcurso;
     private String titulo;
     private int numeroHoras;
     private Set edicions = new HashSet(0);
     private Set cursosForIdcurso = new HashSet(0);
     private Set cursosForPreRequisito = new HashSet(0);

    public Curso() {
    }
    public Curso(String idcurso, String titulo, int numeroHoras) {
        this.idcurso = idcurso;
        this.titulo = titulo;
        this.numeroHoras = numeroHoras;
    }
    public Curso(String idcurso, String titulo, int numeroHoras, Set edicions, Set cursosForIdcurso, Set cursosForPreRequisito) {
       this.idcurso = idcurso;
       this.titulo = titulo;
       this.numeroHoras = numeroHoras;
       this.edicions = edicions;
       this.cursosForIdcurso = cursosForIdcurso;
       this.cursosForPreRequisito = cursosForPreRequisito;
    }
   
    public String getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(String idcurso) {
        this.idcurso = idcurso;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public int getNumeroHoras() {
        return this.numeroHoras;
    }
    
    public void setNumeroHoras(int numeroHoras) {
        this.numeroHoras = numeroHoras;
    }
    public Set getEdicions() {
        return this.edicions;
    }
    
    public void setEdicions(Set edicions) {
        this.edicions = edicions;
    }
    public Set getCursosForIdcurso() {
        return this.cursosForIdcurso;
    }
    
    public void setCursosForIdcurso(Set cursosForIdcurso) {
        this.cursosForIdcurso = cursosForIdcurso;
    }
    public Set getCursosForPreRequisito() {
        return this.cursosForPreRequisito;
    }
    
    public void setCursosForPreRequisito(Set cursosForPreRequisito) {
        this.cursosForPreRequisito = cursosForPreRequisito;
    }

//******************************************************************************
public void Insertar() {

        try {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.getTransaction().begin();
            sesion.save(this);
            sesion.flush();
            sesion.getTransaction().commit();
            sesion.close();
            JOptionPane.showMessageDialog(null, "DATOS INSERTADOS CORRECTAMENTE.", "MENSAJE", JOptionPane.WARNING_MESSAGE, null);
        }catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
}

//------------------------------------------------------------------------------
public void Modificar() {

     try {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.getTransaction().begin();
            sesion.update(this);
            sesion.flush();
            sesion.getTransaction().commit();
            sesion.close();
            JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE.", "MENSAJE", JOptionPane.WARNING_MESSAGE, null);
        }catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
    }
//------------------------------------------------------------------------------
 public void Eliminar() {
          try {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.getTransaction().begin();
            sesion.delete(this);
            sesion.flush();
            sesion.getTransaction().commit();
            sesion.close();
            JOptionPane.showMessageDialog(null, "DATOS ELIMINADOS CORRECTAMENTE.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE, null);
        }catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
    }

//------------------------------------------------------------------------------

public boolean Existe(String id) {

        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();

        Iterator resultado = null;
        Object x = null;

        try {
            resultado = sesion.createSQLQuery("select IDCURSO from curso where IDCURSO ='" + id + "'").list().iterator();

        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }

        while (resultado.hasNext()) {
            x = resultado.next();
            System.out.println("elemento id : " + x.toString());
        }
        sesion.close();
        if (x != null) {
            return true;
        } else {
            return false;
        }

    }
//------------------------------------------------------------------------------
    public List getListCurso(){
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();
        List<Curso> t=null;
        try {
            t=sesion.createSQLQuery("select *from curso").list();
        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
        sesion.flush();
        sesion.close();
        return t;
    }
//------------------------------------------------------------------------------
    public Curso getCurso(String id){
        Curso x = new Curso();
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();
        List<Object[]> t=null;
        try {
            t=sesion.createSQLQuery("select *from curso where IDCURSO = '"+id+"'").list();
        } catch (HibernateException e) {
             System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
         sesion.flush();
         sesion.close();
        if(t.size()>0){
            x.setIdcurso(t.get(0)[0].toString());
            x.setTitulo(t.get(0)[1].toString());
            x.setNumeroHoras(Integer.valueOf(t.get(0)[2].toString()));
            return x;
        }else{
             return null;
        }

    }
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------

//------------------------------------------------------------------------------



}


