package DATOS;
// Generated 18-ago-2011 23:17:44 by Hibernate Tools 3.2.1.GA

import java.sql.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

    private String codigo;
    private int ci;
    private String nombre;
    private Date fechaIngreso;
    private String cargo;
    private Set calificacions = new HashSet(0);
    private Set inscripcions = new HashSet(0);
    private Set edicions = new HashSet(0);

    public Empleado() {
    }

    public Empleado(String codigo, int ci, String nombre, Date fechaIngreso, String cargo) {
        this.codigo = codigo;
        this.ci = ci;
        this.nombre = nombre;
        this.fechaIngreso = fechaIngreso;
        this.cargo = cargo;
    }

    public Empleado(String codigo, int ci, String nombre, Date fechaIngreso, String cargo, Set calificacions, Set inscripcions, Set edicions) {
        this.codigo = codigo;
        this.ci = ci;
        this.nombre = nombre;
        this.fechaIngreso = fechaIngreso;
        this.cargo = cargo;
        this.calificacions = calificacions;
        this.inscripcions = inscripcions;
        this.edicions = edicions;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public int getCi() {
        return this.ci;
    }

    public void setCi(int ci) {
        this.ci = ci;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public String getCargo() {
        return this.cargo;
    }

    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    public Set getCalificacions() {
        return this.calificacions;
    }

    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }

    public Set getInscripcions() {
        return this.inscripcions;
    }

    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }

    public Set getEdicions() {
        return this.edicions;
    }

    public void setEdicions(Set edicions) {
        this.edicions = edicions;
    }

//******************************************************************************
    public void Insertar() {

        try {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.getTransaction().begin();
            sesion.save(this);
            sesion.flush();
            sesion.getTransaction().commit();
            sesion.close();
            JOptionPane.showMessageDialog(null, "DATOS INSERTADOS CORRECTAMENTE.", "MENSAJE", JOptionPane.WARNING_MESSAGE, null);
        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
    }

//------------------------------------------------------------------------------
    public void Modificar() {

        try {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.getTransaction().begin();
            sesion.update(this);
            sesion.flush();
            sesion.getTransaction().commit();
            sesion.close();
            JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE.", "MENSAJE", JOptionPane.WARNING_MESSAGE, null);
        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
    }
//------------------------------------------------------------------------------

    public void Eliminar() {
        try {
            Session sesion = HibernateUtil.getSessionFactory().openSession();
            sesion.getTransaction().begin();
            sesion.delete(this);
            sesion.flush();
            sesion.getTransaction().commit();
            sesion.close();
            JOptionPane.showMessageDialog(null, "DATOS ELIMINADOS CORRECTAMENTE.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE, null);
        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
    }

//------------------------------------------------------------------------------
    public boolean Existe(String id) {

        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();

        Iterator resultado = null;
        Object x = null;

        try {
            resultado = sesion.createSQLQuery("select CODIGO from empleado where CODIGO ='" + id + "'").list().iterator();

        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }

        while (resultado.hasNext()) {
            x = resultado.next();
            System.out.println("elemento id : " + x.toString());
        }
        sesion.close();
        if (x != null) {
            return true;
        } else {
            return false;
        }

    }
//------------------------------------------------------------------------------

    public List getListEmpleado() {
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();
        List<Empleado> t = null;
        try {
            t = sesion.createSQLQuery("select *from empleado").list();
        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
        sesion.flush();
        sesion.close();
        return t;
    }
//------------------------------------------------------------------------------

    public Empleado getEmpleado(String id) {
        Empleado x = new Empleado();
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        sesion.beginTransaction();
        List<Object[]> t = null;
        try {
            t = sesion.createSQLQuery("select *from empleado where CODIGO = '" + id + "'").list();
        } catch (HibernateException e) {
            System.out.println("¡¡¡ ERROR EN LA CONSULTA !!! ---> " + e.toString());
        }
        sesion.flush();
        sesion.close();
        if (t.size() > 0) {

            x.setCodigo(t.get(0)[0].toString());
            x.setCi(Integer.valueOf(t.get(0)[1].toString()));
            x.setNombre(t.get(0)[2].toString());
            Date fecha = Date.valueOf(t.get(0)[3].toString());
            x.setFechaIngreso(fecha);
            x.setCargo(t.get(0)[4].toString());
            return x;

        } else {
            return null;
        }

    }
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
}


