package DATOS;
// Generated 19-ago-2011 9:46:36 by Hibernate Tools 3.2.1.GA



/**
 * RequisitosId generated by hbm2java
 */
public class RequisitosId  implements java.io.Serializable {


     private String idcurso;
     private String pre_requisito;

    public RequisitosId() {
    }

    public RequisitosId(String idcurso, String pre_requisito) {
        this.idcurso = idcurso;
        this.pre_requisito = pre_requisito;
    }

    public String getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(String idcurso) {
        this.idcurso = idcurso;
    }

    public String getPre_requisito() {
        return pre_requisito;
    }

    public void setPre_requisito(String pre_requisito) {
        this.pre_requisito = pre_requisito;
    }
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final RequisitosId other = (RequisitosId) obj;
        if ((this.idcurso == null) ? (other.idcurso != null) : !this.idcurso.equals(other.idcurso)) {
            return false;
        }
        if ((this.pre_requisito == null) ? (other.pre_requisito != null) : !this.pre_requisito.equals(other.pre_requisito)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 41 * hash + (this.idcurso != null ? this.idcurso.hashCode() : 0);
        hash = 41 * hash + (this.pre_requisito != null ? this.pre_requisito.hashCode() : 0);
        return hash;
    }
   
}


